'use client';

import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export default function Dashboard() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <header className="mb-12 text-center">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
            RadiologyAI Diagnostic Platform
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
            Advanced medical imaging analysis powered by AI. Upload up to 200 medical images, 
            including DICOM files, for comprehensive diagnostic reporting using Sonnet 4.
          </p>
          <div className="flex justify-center gap-3 mt-4">
            <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
              DICOM Support
            </Badge>
            <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200">
              Batch Processing
            </Badge>
            <Badge variant="outline" className="bg-purple-50 text-purple-700 border-purple-200">
              AI-Powered Analysis
            </Badge>
          </div>
        </header>

        {/* Main Navigation Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
          {/* Upload Images Card */}
          <Card className="hover:shadow-lg transition-shadow duration-300 border-0 bg-white/70 backdrop-blur-sm">
            <CardHeader className="pb-4">
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
                <div className="w-6 h-6 bg-blue-600 rounded"></div>
              </div>
              <CardTitle className="text-xl font-semibold text-gray-900">
                Upload Medical Images
              </CardTitle>
              <CardDescription className="text-gray-600">
                Upload up to 200 medical images including DICOM files. 
                Automatic DICOM to PNG conversion included.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Link href="/upload">
                <Button className="w-full bg-blue-600 hover:bg-blue-700 text-white">
                  Start Upload Process
                </Button>
              </Link>
            </CardContent>
          </Card>

          {/* View Reports Card */}
          <Card className="hover:shadow-lg transition-shadow duration-300 border-0 bg-white/70 backdrop-blur-sm">
            <CardHeader className="pb-4">
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
                <div className="w-6 h-6 bg-green-600 rounded"></div>
              </div>
              <CardTitle className="text-xl font-semibold text-gray-900">
                Diagnostic Reports
              </CardTitle>
              <CardDescription className="text-gray-600">
                View comprehensive diagnostic reports generated by AI analysis 
                with professional medical insights.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Link href="/reports">
                <Button className="w-full bg-green-600 hover:bg-green-700 text-white">
                  View Reports
                </Button>
              </Link>
            </CardContent>
          </Card>

          {/* System Configuration Card */}
          <Card className="hover:shadow-lg transition-shadow duration-300 border-0 bg-white/70 backdrop-blur-sm">
            <CardHeader className="pb-4">
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
                <div className="w-6 h-6 bg-purple-600 rounded"></div>
              </div>
              <CardTitle className="text-xl font-semibold text-gray-900">
                System Configuration
              </CardTitle>
              <CardDescription className="text-gray-600">
                Customize AI system prompts and diagnostic parameters 
                for specialized medical analysis.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Link href="/config">
                <Button variant="outline" className="w-full border-purple-200 text-purple-700 hover:bg-purple-50">
                  Configure System
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>

        {/* Key Features Section */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-8 text-center">
            Platform Capabilities
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <div className="text-center p-6 bg-white/50 backdrop-blur-sm rounded-xl">
              <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <div className="w-8 h-8 bg-blue-600 rounded"></div>
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">DICOM Processing</h3>
              <p className="text-sm text-gray-600">
                Automatic detection and conversion of DICOM medical imaging files
              </p>
            </div>

            <div className="text-center p-6 bg-white/50 backdrop-blur-sm rounded-xl">
              <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <div className="w-8 h-8 bg-green-600 rounded"></div>
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">Batch Analysis</h3>
              <p className="text-sm text-gray-600">
                Intelligent batching of up to 20 images per AI analysis request
              </p>
            </div>

            <div className="text-center p-6 bg-white/50 backdrop-blur-sm rounded-xl">
              <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <div className="w-8 h-8 bg-purple-600 rounded"></div>
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">AI Diagnostics</h3>
              <p className="text-sm text-gray-600">
                Advanced medical image analysis using Claude Sonnet 4
              </p>
            </div>

            <div className="text-center p-6 bg-white/50 backdrop-blur-sm rounded-xl">
              <div className="w-16 h-16 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <div className="w-8 h-8 bg-orange-600 rounded"></div>
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">Professional Reports</h3>
              <p className="text-sm text-gray-600">
                Comprehensive diagnostic reports with PDF export capability
              </p>
            </div>
          </div>
        </section>

        {/* Workflow Overview */}
        <section className="bg-white/50 backdrop-blur-sm rounded-xl p-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-8 text-center">
            Diagnostic Workflow
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
            {[
              { step: '1', title: 'Upload', desc: 'Upload medical images' },
              { step: '2', title: 'Convert', desc: 'DICOM to PNG conversion' },
              { step: '3', title: 'Batch', desc: 'Organize into batches' },
              { step: '4', title: 'Analyze', desc: 'AI diagnostic analysis' },
              { step: '5', title: 'Report', desc: 'Generate comprehensive report' }
            ].map((item, index) => (
              <div key={item.step} className="text-center">
                <div className="w-12 h-12 bg-blue-600 text-white rounded-full flex items-center justify-center mx-auto mb-3 font-bold">
                  {item.step}
                </div>
                <h3 className="font-semibold text-gray-900 mb-1">{item.title}</h3>
                <p className="text-sm text-gray-600">{item.desc}</p>
                {index < 4 && (
                  <div className="hidden md:block w-full h-0.5 bg-blue-200 mt-4"></div>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Footer */}
        <footer className="mt-12 text-center text-gray-500 dark:text-gray-400">
          <p>
            RadiologyAI Platform - Advanced Medical Imaging Analysis
          </p>
          <p className="text-sm mt-2">
            AI analysis is supplementary to professional medical diagnosis
          </p>
        </footer>
      </div>
    </div>
  );
}